name: Vitest Unit Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Unit tests
        run: npm run test:unit
        env:
          CI: true
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
          SECRET_API_URL: ${{ secrets.SECRET_API_URL }}
          SECRET_API_MODELS: ${{ secrets.SECRET_API_MODELS }}
          SECRET_STATUS_URL: ${{ secrets.SECRET_STATUS_URL }}
          SECRET_FALLBACK_DOMAIN: ${{ secrets. SECRET_FALLBACK_DOMAIN }}
          SECRET_FALLBACK_URL: ${{ secrets.SECRET_FALLBACK_URL }}
          SECRET_FALLBACK_AJAX_URL: ${{ secrets.SECRET_FALLBACK_AJAX_URL }}
